include_guard(GLOBAL)

include(FetchContent)

set(BINJA_QT_VERSION "6.8.2" CACHE STRING "Qt version for qt-artifacts")
set(BINJA_QT_PLATFORM "" CACHE STRING "Override qt-artifacts platform slug (macosx/linux/linux-arm/win64)")
set(BINJA_QT_DIR "" CACHE PATH "Root of extracted qt-artifacts directory")
set(BINJA_QT_URL "" CACHE STRING "Direct URL to qt-artifacts archive")
set(BINJA_QT_SHA256 "" CACHE STRING "SHA256 for qt-artifacts archive")
set(BINJA_QT_CMAKE_DIR "" CACHE PATH "Direct path to Qt6 cmake directory")

set(_BINJA_QT_BASE_URL "https://github.com/Vector35/qt-artifacts/releases/download")

function(binja_qt_detect_platform out_var)
    if(BINJA_QT_PLATFORM)
        set(${out_var} "${BINJA_QT_PLATFORM}" PARENT_SCOPE)
        return()
    endif()

    if(APPLE)
        set(${out_var} "macosx" PARENT_SCOPE)
    elseif(WIN32)
        set(${out_var} "win64" PARENT_SCOPE)
    else()
        string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _qt_proc)
        if(_qt_proc MATCHES "^(aarch64|arm64)")
            set(${out_var} "linux-arm" PARENT_SCOPE)
        else()
            set(${out_var} "linux" PARENT_SCOPE)
        endif()
    endif()
endfunction()

function(binja_qt_find_cmake_dir out_var root_dir)
    set(_qt_root "${root_dir}")
    if(EXISTS "${_qt_root}/${BINJA_QT_VERSION}/clang_64")
        set(_qt_root "${_qt_root}/${BINJA_QT_VERSION}")
    elseif(EXISTS "${_qt_root}/${BINJA_QT_VERSION}/gcc_64")
        set(_qt_root "${_qt_root}/${BINJA_QT_VERSION}")
    elseif(EXISTS "${_qt_root}/${BINJA_QT_VERSION}/msvc2022_64")
        set(_qt_root "${_qt_root}/${BINJA_QT_VERSION}")
    endif()

    set(_host_candidates "")
    if(APPLE)
        list(APPEND _host_candidates clang_64)
    elseif(WIN32)
        list(APPEND _host_candidates msvc2022_64)
    else()
        list(APPEND _host_candidates gcc_64)
    endif()
    list(APPEND _host_candidates clang_64 gcc_64 msvc2022_64)

    foreach(_host IN LISTS _host_candidates)
        set(_candidate "${_qt_root}/${_host}/lib/cmake/Qt6/Qt6Config.cmake")
        if(EXISTS "${_candidate}")
            get_filename_component(_cmake_dir "${_candidate}" DIRECTORY)
            set(${out_var} "${_cmake_dir}" PARENT_SCOPE)
            return()
        endif()
    endforeach()

    message(FATAL_ERROR "Qt6Config.cmake not found under ${root_dir}. Set BINJA_QT_CMAKE_DIR explicitly.")
endfunction()

function(binja_qt_configure)
    if(BINJA_QT_CMAKE_DIR)
        list(PREPEND CMAKE_PREFIX_PATH "${BINJA_QT_CMAKE_DIR}")
        set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" PARENT_SCOPE)
        return()
    endif()

    if(NOT BINJA_QT_DIR)
        if(NOT BINJA_QT_URL)
            binja_qt_detect_platform(_qt_platform)
            set(_qt_asset "qt${BINJA_QT_VERSION}-${_qt_platform}.zip")
            set(BINJA_QT_URL "${_BINJA_QT_BASE_URL}/${BINJA_QT_VERSION}/${_qt_asset}")
        endif()

        if(POLICY CMP0169)
            cmake_policy(SET CMP0169 OLD)
        endif()

        if(BINJA_QT_SHA256)
            FetchContent_Declare(binja_qt
                URL ${BINJA_QT_URL}
                URL_HASH SHA256=${BINJA_QT_SHA256}
                DOWNLOAD_EXTRACT_TIMESTAMP TRUE
            )
        else()
            FetchContent_Declare(binja_qt
                URL ${BINJA_QT_URL}
                DOWNLOAD_EXTRACT_TIMESTAMP TRUE
            )
        endif()

        FetchContent_GetProperties(binja_qt)
        if(NOT binja_qt_POPULATED)
            FetchContent_Populate(binja_qt)
        endif()
        set(BINJA_QT_DIR "${binja_qt_SOURCE_DIR}" CACHE PATH "Root of extracted qt-artifacts directory" FORCE)
    endif()

    binja_qt_find_cmake_dir(_qt_cmake_dir "${BINJA_QT_DIR}")
    set(Qt6_DIR "${_qt_cmake_dir}" CACHE PATH "Qt6 cmake directory" FORCE)

    get_filename_component(_qt_cmake_parent "${_qt_cmake_dir}" DIRECTORY)
    get_filename_component(_qt_lib_dir "${_qt_cmake_parent}" DIRECTORY)
    set(Qt6Core_DIR "${_qt_cmake_parent}/Qt6Core" CACHE PATH "Qt6Core cmake directory" FORCE)
    set(Qt6Gui_DIR "${_qt_cmake_parent}/Qt6Gui" CACHE PATH "Qt6Gui cmake directory" FORCE)
    set(Qt6Widgets_DIR "${_qt_cmake_parent}/Qt6Widgets" CACHE PATH "Qt6Widgets cmake directory" FORCE)
    set(Qt6Svg_DIR "${_qt_cmake_parent}/Qt6Svg" CACHE PATH "Qt6Svg cmake directory" FORCE)
    get_filename_component(_qt_root_dir "${_qt_lib_dir}" DIRECTORY)
    if(EXISTS "${_qt_root_dir}/bin/qmake")
        set(QMAKE_COMMAND "${_qt_root_dir}/bin/qmake" CACHE FILEPATH "Qt qmake" FORCE)
    elseif(EXISTS "${_qt_root_dir}/bin/qmake6")
        set(QMAKE_COMMAND "${_qt_root_dir}/bin/qmake6" CACHE FILEPATH "Qt qmake" FORCE)
    endif()
    if(CMAKE_PREFIX_PATH)
        set(_qt_prefix "${_qt_cmake_dir};${CMAKE_PREFIX_PATH}")
    else()
        set(_qt_prefix "${_qt_cmake_dir}")
    endif()
    list(REMOVE_DUPLICATES _qt_prefix)
    set(CMAKE_PREFIX_PATH "${_qt_prefix}" CACHE STRING "CMake prefix path" FORCE)
endfunction()
